# Generated by Django 2.1.9 on 2020-04-28 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='Blog_Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
